version: '3.4'

services:
  node1:
    build: .
    entrypoint: ./docker-entrypoint.sh
    command: init
    ports:
      - 4000
    environment:
      ERLANG_COOKIE: secret
      NODE_BASENAME: service
      CONNECT_TO_NODENAME: cluster_test_node2_1

  node2:
    build: .
    entrypoint: ./docker-entrypoint.sh
    command: init
    ports:
      - 4000
    environment:
      ERLANG_COOKIE: secret
      NODE_BASENAME: service
      CONNECT_TO_NODENAME: cluster_test_node1_1
